// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3, arg4);
}

export function DelKey(arg1) {
  return window['go']['main']['App']['DelKey'](arg1);
}

export function DeleteAllKeys() {
  return window['go']['main']['App']['DeleteAllKeys']();
}

export function GetKey(arg1) {
  return window['go']['main']['App']['GetKey'](arg1);
}

export function GetKeys() {
  return window['go']['main']['App']['GetKeys']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SetKey(arg1, arg2) {
  return window['go']['main']['App']['SetKey'](arg1, arg2);
}
