// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DelKey(arg1:string):Promise<void>;

export function DeleteAllKeys():Promise<void>;

export function GetKey(arg1:string):Promise<main.KeyValue>;

export function GetKeys():Promise<Array<main.KeyValue>>;

export function Logout():Promise<void>;

export function SetKey(arg1:string,arg2:string):Promise<void>;
